name: commit-binary-to-github
description: commit binary to github repo - which triggers to npm publish
inputs:
  version:
    description: 'choose version'
    required: true
    default: 'v0.30.0'
  platform:
    description: 'choose platform'
    required: true
    default: 'darwin-arm64'

runs:
  using: "composite"
  steps:
    - name: checkout
      uses: actions/checkout@v4

    # GITHUB_ENV operates like a .env file
    - name: extract version
      run: |
        VERSION=${{inputs.version}}
        CLEAN_VERSION=${{VERSION#v }}
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "CLEAN_VERSION=$CLEAN_VERSION" >> $GITHUB_ENV
    - name: node
      uses: actions/setup-node@v4
      with:
        node-version: 16.x
    - name: download and extract tarball
      run: |
        curl -L -o tarball.tar.gz https://github.com/dotenvx/dotenvx/releases/download/${{ env.VERSION }}/dotenvx-${{ env.CLEAN_VERSION }}-${{ inputs.platform }}.tar.gz
        mkdir -p output
        tar -xzvf tarball.tar.gz -C output --strip-components=1
    - name: checkout target repo
      uses: actions/checkout@v4
      with:
        repository: "dotenvx/dotenvx-${{ inputs.platform }}"
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        path: "dotenvx-${{ inputs.platform }}"
    - name: copy dotenvx binary to repo
      run: |
        mkdir -p dotenvx-${{ inputs.platform }}
        cp -r output/* dotenvx-${{ inputs.platform }}/
    - name: set version, commit, and push
      run: |
        cd dotenvx-${{ inputs.platform }}
        npm version ${{ env.CLEAN_VERSION }} --no-git-tag-version
        git config --global user.name 'motdotenv'
        git config --global user.email 'mot@dotenv.org'
        git add .
        git commit -m "${{ env.VERSION }}"
        git tag "${{ env.VERSION }}"
        git push origin HEAD --tags
