name: bins

on:
  push:
    tags:
      - v*.*.*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      # https://news.ycombinator.com/item?id=32388964
      # https://github.com/procursusteam/ldid
      # https://www.pulumi.com/blog/nodejs-binaries-with-pkg/
      # https://github.com/pulumi/pulumi-aws-static-website/blob/main/.github/workflows/release.yaml
      - name: ldid for macos binary building
        uses: MOZGIII/install-ldid-action@v1
        with:
          tag: v2.1.5-procursus2

      - name: npm install
        run: npm install

      - name: pkg
        run: |
          echo "pkg-ing"
          ./node_modules/.bin/pkg . --no-bytecode --public-packages "*" --public --target node16-macos-arm64 --output bin/darwin-arm64/git-dotenv
          echo "dist-ing"
          mkdir -p dist
          tar --gzip -cf ./dist/git-dotenv-darwin-arm64.tar.gz README.md -C bin/darwin-arm64/ .

      - name: create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.tar.gz
    strategy:
      fail-fast: true
