name: bins

on: push

jobs:
  bins:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: ldid for macos binary building
      uses: MOZGIII/install-ldid-action@<action-version>
      with:
        tag: v2.1.5-procursus2

    - name: ldid
      run: ldid

    - name: node
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: npm install
      run: npm install

    - name: pkg
      run: npm run pkg

    - name: permission
      run: chmod +x bin/git-dotenv

    - name: create release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: bin/git-dotenv
