name: ci

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: node
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: npm install
      run: npm install

    - name: pkg
      run: npm run pkg

    - name: upload binary
      uses: actions/upload-artifact@v2
      with:
        name: git-dotenv
        path: dist/git-dotenv


