name: ci

on: push

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: node
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: npm install
      run: npm install

    - name: pkg
      run: npm run pkg

    - name: permission
      run: chmod +x dist/git-dotenv

    - name: create release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/git-dotenv
